/**
 * SupplySense — India-edition static fallback data.
 * Mirrors the mock data generated by backend/data.py (seed=42).
 * Used when the backend is offline or for instant first-render.
 * All entities are India-specific matching the real DB.
 */

export type RiskLevel = 'critical' | 'warning' | 'healthy'

export const kpis = [
  { label: 'Active shipments', value: '15', detail: '5 POs in transit across India', trend: 'Live' },
  { label: 'Inventory at risk', value: '8', detail: 'SKUs at or below reorder point', trend: '+risk', risk: true },
  { label: 'Supplier reliability', value: '88%', detail: 'Across 10 India suppliers', trend: 'Live' },
  { label: 'Avg. lead time', value: '8.5d', detail: 'Domestic supplier mean', trend: 'Live' },
]

// Mirrors inventory_levels JOIN components JOIN warehouses (first 4 critical rows)
export const inventory = [
  {
    sku: 'ITEM-001',
    name: 'Lithium-Ion Battery Pack',
    warehouse: 'Bhiwandi, Maharashtra',
    stock: 42,
    cover: '2 days',
    demand: '+52%',
    status: 'critical' as RiskLevel,
  },
  {
    sku: 'ITEM-002',
    name: 'Microcontroller Unit',
    warehouse: 'Chennai, Tamil Nadu',
    stock: 98,
    cover: '5 days',
    demand: '+31%',
    status: 'critical' as RiskLevel,
  },
  {
    sku: 'ITEM-003',
    name: 'Chassis Assembly',
    warehouse: 'Manesar, Haryana',
    stock: 210,
    cover: '9 days',
    demand: '+18%',
    status: 'warning' as RiskLevel,
  },
  {
    sku: 'ITEM-004',
    name: 'Brushless DC Motor',
    warehouse: 'Bengaluru, Karnataka',
    stock: 560,
    cover: '22 days',
    demand: '+7%',
    status: 'healthy' as RiskLevel,
  },
]

// Mirrors suppliers table sorted by delivery_performance_score DESC
export const suppliers = [
  {
    name: 'Konkan Components Pvt Ltd',
    region: 'Mumbai, Maharashtra',
    score: 62,
    issue: 'JNPT port exposure',
    status: 'critical' as RiskLevel,
  },
  {
    name: 'Tapi Component Works',
    region: 'Surat, Gujarat',
    score: 74,
    issue: 'Lead-time variance',
    status: 'warning' as RiskLevel,
  },
  {
    name: 'Deccan Manufacturing Co',
    region: 'Pune, Maharashtra',
    score: 88,
    issue: 'On target',
    status: 'healthy' as RiskLevel,
  },
  {
    name: 'Bengaluru Circuit Systems',
    region: 'Bengaluru, Karnataka',
    score: 94,
    issue: 'On target',
    status: 'healthy' as RiskLevel,
  },
]

// Mirrors warehouses table with utilization as 0–100 integer
export const warehouses = [
  { city: 'Mumbai Distribution Hub', code: 'WH-001', utilization: 87, status: 'warning' as RiskLevel },
  { city: 'South India Fulfillment Center', code: 'WH-002', utilization: 72, status: 'healthy' as RiskLevel },
  { city: 'North India Logistics Hub', code: 'WH-003', utilization: 91, status: 'critical' as RiskLevel },
  { city: 'East India Regional Warehouse', code: 'WH-004', utilization: 58, status: 'healthy' as RiskLevel },
  { city: 'Bengaluru Tech Corridor Depot', code: 'WH-005', utilization: 65, status: 'healthy' as RiskLevel },
]

// Mirrors purchase_orders JOIN — PO-889 is always first (disruption target)
export const shipments = [
  {
    po: 'PO-889',
    item: 'Lithium-Ion Battery Pack',
    route: 'JNPT-Mumbai Port Corridor',
    eta: '6d',
    status: 'In Transit',
  },
  {
    po: 'PO-800',
    item: 'Microcontroller Unit',
    route: 'Chennai Port Corridor',
    eta: '3d',
    status: 'In Transit',
  },
  {
    po: 'PO-801',
    item: 'Chassis Assembly',
    route: 'Golden Quadrilateral Highway Corridor',
    eta: '1d',
    status: 'Pending',
  },
  {
    po: 'PO-802',
    item: 'Wiring Harness',
    route: 'Mundra Port Route',
    eta: '8d',
    status: 'Delayed',
  },
]

// Battery demand forecast data (India EV/electronics market context)
export const demandPoints = [22, 25, 24, 30, 33, 32, 38, 42, 47, 52, 58, 66]
export const forecastPoints = [66, 72, 79, 85, 92, 101]

// PRD §11 demo script — the 4 required NL queries + sourcing + extras
export const promptOptions = [
  'Which products are at risk of going out of stock?',
  'Which suppliers are most likely to miss deliveries next week?',
  'Which warehouse should fulfill this order?',
  'What is causing today\'s biggest supply chain disruption?',
  'Recommend alternate suppliers for Lithium-Ion Battery Pack',
]

// Offline fallback responses — India-specific, mirrors PRD §11 demo script
export const copilotResponses: Record<string, { title: string; summary: string; bullets: string[] }> = {
  'Which products are at risk of going out of stock?': {
    title: 'Stockout risk ranked',
    summary:
      'Lithium-Ion Battery Pack (ITEM-001) is projected to breach safety stock in 2 days at Bhiwandi (Mumbai). PO-889 delay via JNPT-Mumbai Port Corridor makes the shortfall critical.',
    bullets: [
      'ITEM-001 Lithium-Ion Battery Pack · 2 days cover · Bhiwandi, Maharashtra',
      'ITEM-002 Microcontroller Unit · 5 days cover · Chennai, Tamil Nadu',
      'ITEM-003 Chassis Assembly · 9 days cover · Manesar (Delhi NCR)',
    ],
  },
  'Which suppliers are most likely to miss deliveries next week?': {
    title: 'Supplier risk drivers',
    summary:
      'Konkan Components Pvt Ltd (Mumbai) is at highest risk — JNPT port congestion adds 3–5 day delay. Tapi Component Works (Surat) has elevated lead-time variance on Mundra port route.',
    bullets: [
      'Konkan Components · Score 62 · JNPT port exposure · 6d lead time',
      'Tapi Component Works · Score 74 · Mundra route variance · 9d lead time',
      'Sabarmati Industrial Supply · Score 78 · Pending PO on highway corridor',
    ],
  },
  'Which warehouse should fulfill this order?': {
    title: 'Warehouse allocation recommendation',
    summary:
      'North India Logistics Hub (Manesar, Haryana) is recommended for NCR orders — it has the highest throughput capacity. For South India, South India Fulfillment Center (Chennai) is optimal with 72% utilization.',
    bullets: [
      'Manesar (WH-003) · 91% utilized · Best for NCR / North India orders',
      'Chennai (WH-002) · 72% utilized · Preferred for South India',
      'Bhiwandi (WH-001) · 87% utilized · Good for West India / export via JNPT',
    ],
  },
  "What is causing today's biggest supply chain disruption?": {
    title: 'Disruption root cause',
    summary:
      'JNPT (Jawaharlal Nehru Port, Navi Mumbai) operations are disrupted due to severe monsoon flooding, pausing container handling for an estimated 48 hours and blocking PO-889.',
    bullets: [
      'JNPT handles ~55% of India\'s containerised cargo — high impact',
      'PO-889: 500× Lithium-Ion Battery Pack stuck in corridor',
      'Projected stockout at Mumbai Distribution Hub within 2 days',
    ],
  },
  'Recommend alternate suppliers for Lithium-Ion Battery Pack': {
    title: 'Alternate sourcing ready',
    summary:
      'Three qualified alternate suppliers can cover the 500-unit Lithium-Ion Battery Pack order. Deccan Manufacturing Co (Pune) offers the best resilience-adjusted option via road corridor.',
    bullets: [
      'Deccan Manufacturing Co · Pune · 5d lead · 92% fulfillment · Road corridor',
      'Bengaluru Circuit Systems · Bengaluru · 7d lead · 96% fulfillment · Rail + Road',
      'Sabarmati Industrial Supply · Ahmedabad · 4d lead · 85% fulfillment · Mundra route',
    ],
  },
  rerouted: {
    title: 'Procurement action created',
    summary: 'Deccan Manufacturing Co (Pune) has been selected as the alternate source for PO-889.',
    bullets: [
      '500 units reserved · Expected delivery via Pune-Mumbai highway corridor',
      'Delivery target: Bhiwandi Distribution Hub · July 24, 2026',
      'Exposure avoided: estimated ₹1.2 Cr stockout risk mitigated',
    ],
  },
  __greeting__: {
    title: 'SupplySense AI Assistant',
    summary: 'Hello! I\'m your AI supply chain assistant for India operations. I can help with inventory risk analysis, supplier performance tracking, warehouse optimization, and disruption simulation. Try one of the preset queries or tell me what you\'d like to explore.',
    bullets: ['Try: "Which products are at risk of going out of stock?"', 'Try: "Which suppliers are most likely to miss deliveries?"', 'Try: "Recommend alternate suppliers for Battery Pack"'],
  },
  __help__: {
    title: 'How I can help',
    summary: 'I analyze your Indian supply chain network across inventory, suppliers, warehouses, and shipments. Ask me about stockout risks, supplier scores, warehouse allocation, or JNPT disruption impact. I can also simulate disruption scenarios to test network resilience.',
    bullets: ['Inventory risk analysis · Stockout prediction', 'Supplier performance · Lead-time variance monitoring', 'Disruption simulation · JNPT port scenario', 'Warehouse allocation optimization'],
  },
  __default__: {
    title: 'SupplySense analysis',
    summary: 'I\'ve received your query. For the most accurate analysis of your Indian supply chain, try one of my specific prompts above. I can analyze inventory risk, supplier performance, warehouse utilization, and disruption impact in detail.',
    bullets: ['Use the preset prompts for specific analysis', 'Or rephrase your question about supply chain operations'],
  },
}
